In [1]:
import torch
print(torch.__version__)

1.13.1+cpu


In [2]:
## Introduction to Tensors

#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#vectors

vector = torch.tensor([1,2])
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#MATRIX

MATRIX = torch.tensor([[1,2],
                      [3,4]])
MATRIX.ndim

2

In [8]:
MATRIX.shape

torch.Size([2, 2])

In [9]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR.ndim

3

In [10]:
TENSOR.shape

torch.Size([1, 3, 3])

In [11]:
#Random Tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1434, 0.3175, 0.3923, 0.3947],
        [0.1891, 0.8517, 0.9641, 0.7857],
        [0.8677, 0.5099, 0.5220, 0.6091]])

In [12]:
#create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [13]:
## Zeros and Ones

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
## range of tensors
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
torch.arange(start=1, end=11, step=2)

tensor([1, 3, 5, 7, 9])

In [17]:
#creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
#Tensors datatypes
#float32 is the default data type in PyTorch tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = None,
                              device = None,  #default cpu
                              requires_grad = False) #track gradients

float_32_tensor.dtype

torch.float32

### 3 Big errors one will run into with PyTorch and Deep Learning
1. Tensors not right data type
2. Tensors not right shape
3. Tensors not on the right device

In [19]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from Tensors
### tensor.dtype
### tensor.shape
### tensor.device

In [20]:
# Manipulating Tensors
#----> Addition, Substraction, Multiplication, Division
#----> Matrix Multiplication

In [21]:
vector+10

tensor([11, 12])

In [22]:
vector*10

tensor([10, 20])

In [23]:
vector-10

tensor([-9, -8])

In [24]:
#PyTorch inbuilt functions
torch.mul(vector,10)

tensor([10, 20])

## Matrix Multiplication
Element wise Multiplication
Matrix Multiplication(Dot Product)

In [25]:
tensor = torch.tensor([1,2,3])
tensor*tensor

tensor([1, 4, 9])

In [26]:
%%time
tensor.matmul(tensor)

Wall time: 999 µs


tensor(14)

### Two main rules that needs to satisfy for matrix multiplication
1. The inner dimension must match
2. The resulting matrix has the shape of the outer dimension